import styles from './list.module.css'
import Head from 'next/head'
import { Header } from '@components/header'
import { Search } from '@components/search/search'
import { Filter } from '@components/filter/filter'
import { Card } from '@components/card/card'

export default function List() {
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <content className={styles.content}>
          <div className={styles.controls}>
            <Search />
            <Filter />
          </div>
          <div className={styles.grid}>
            <Card />
            <Card />
            <Card />
          </div>
        </content>
      </main>
    </>
  )
}
