import { useEffect, useState } from 'react'
import Head from 'next/head'

import { Search } from '@components/search/search'
import { Filter } from '@components/filter/filter'
import { Card } from '@components/card/card'
import { mapCountries } from '@mappers/map-countries'

import styles from './list.module.css'

function List({ countries: countryList }) {
  const [countries, setCountries] = useState(countryList)
  const [filter, setFilter] = useState('')
  const [search, setSearch] = useState('')

  const handleSearch = (value) => setSearch(value)

  const handleFilter = (value) => setFilter(value)

  const reset = () => setCountries(countryList)

  useEffect(() => {
    if (!search && !filter) return reset()

    const list = countryList.filter(({ name, region }) => {
      if (search && filter)
        return name.toLowerCase() === search.toLowerCase() && region === filter

      if (!search && filter) return region === filter

      if (search && !filter) return name.toLowerCase() === search.toLowerCase()
    })
    setCountries(list)
  }, [search, filter])

  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.content}>
          <div className={styles.controls}>
            <Search onSearch={handleSearch} />
            <Filter onFilter={handleFilter} />
          </div>
          <div className={styles.grid}>
            {(countries || []).map((country) => (
              <Card {...country} key={country.name} />
            ))}
            {!countries || (!countries.length && 'No Data')}
          </div>
        </div>
      </div>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://restcountries.com/v3.1/all')
  const countries = await res.json()

  return {
    props: {
      countries: mapCountries(countries),
    },
  }
}

export default List
